In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# drop obvious irrelevant columns
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import numpy as np

In [5]:
cat_cols = data.select_dtypes(include="object").columns
num_cols = data.drop("Exited", axis=1).select_dtypes(np.number).columns 

X = data.drop("Exited", axis=1)
y = data["Exited"]
print(num_cols)

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [18]:
cat_pipe = Pipeline(
    steps = [
        ("cat_imputer", SimpleImputer(strategy="most_frequent")),
        ("cat_encoder", OneHotEncoder())
    ]
)

num_pipe = Pipeline(
    steps = [
        ("num_imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_pipe, num_cols),
        ("cat", cat_pipe, cat_cols)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [20]:
X_train = preprocessor.fit_transform(X_train, y_train)
X_test  = preprocessor.transform(X_test)

In [ ]:
geography = preprocessor.named_transformers_["cat"].named_steps["cat_encoder"].categories_[0].tolist()

['France', 'Germany', 'Spain']

In [8]:
X_train_df = pd.DataFrame(X_train.toarray() if hasattr(X_train, "toarray") else X_train, columns = preprocessor.get_feature_names_out())
X_test_df = pd.DataFrame(X_test.toarray() if hasattr(X_test, "toarray") else X_test, columns = preprocessor.get_feature_names_out())

In [9]:
# Serialize the preprocessor
import joblib
joblib.dump(preprocessor, "preprocessor.joblib", compress=3)

loaded_preprocessor = joblib.load("preprocessor.joblib")

In [10]:
loaded_preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('num_imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary'],
      dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('cat_imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('cat_encoder',
                                                  OneHotEncoder())]),
                                 Index(['Geography', 'Gender'], dtype='object'))])

### ANN Implementation with tensorflow

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\Gen_AI_with_Krish\ANN_implementation\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [12]:
model_tf = Sequential(
    [
        Dense(64, activation="relu", input_shape=(X_train.shape[1],)), # First Hidden Layer, connected with input layer,
        Dense(32, activation="relu"), ## Hidden 2
        Dense(1, activation="sigmoid"), ## output layer
    ]
)

model_tf.summary()

WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\Gen_AI_with_Krish\ANN_implementation\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                896

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 3009 (11.75 KB)
Trainable params: 3009 (11.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# compile the model
model_tf.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss="binary_crossentropy", metrics=["accuracy"])

In [14]:
"m".upper()

'M'

In [15]:
## Set Up the Tensorboard
import os
log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [16]:
# Set up Eqrly Stopping
early_stopping_callback = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

In [17]:
### Train the model
history = model_tf.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\Gen_AI_with_Krish\ANN_implementation\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\HP\OneDrive\Desktop\Gen_AI_with_Krish\ANN_implementation\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 9s 13ms/step - loss: 0.3889 - accuracy: 0.8391 - val_loss: 0.3504 - val_accuracy: 0.8550
Epoch 2/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3541 - accuracy: 0.8540 - val_loss: 0.3387 - val_accuracy: 0.8605
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3460 - accuracy: 0.8600 - val_loss: 0.3441 - val_accuracy: 0.8615
Epoch 4/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3428 - accuracy: 0.8601 - val_loss: 0.3402 - val_accuracy: 0.8660
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3386 - accuracy: 0.8608 - val_loss: 0.3401 - val_accuracy: 0.8670
Epoch 6/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3368 - accuracy: 0.8625 - val_loss: 0.3465 - val_accuracy: 0.8570
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3375 - accuracy: 0.8615 - val_loss: 0.3396 - val_accuracy: 0.8680
Epoch 8/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3329 - accuracy: 0.8631 - val_loss: 0.3454 - val_accuracy: 0.8545
Epoch 9/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3333 - accuracy: 0.8622 - val_loss: 0.3413 - val_accuracy: 0.8605
Epoch 10/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3292 - accuracy: 0.8656 - val_loss: 0.3407 - val_accuracy: 0.8660
Epoch 11/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3294 - accuracy: 0.8637 - val_loss: 0.3422 - val_accuracy: 0.8605
Epoch 12/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3273 - accuracy: 0.8656 - val_loss: 0.3397 - val_accuracy: 0.8605

In [18]:
model_tf.save("model_tf.h5")

c:\Users\HP\OneDrive\Desktop\Gen_AI_with_Krish\ANN_implementation\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [19]:
## Load Tensorboard Extension
%load_ext tensorboard

In [23]:
%tensorboard --logdir logs/fit20260323-155928

Reusing TensorBoard on port 6006 (pid 18360), started 0:16:06 ago. (Use '!kill 18360' to kill it.)

Caching the list of root modules, please wait!
(This will only be done once - type '%rehashx' to reset cache!)

# building with pytorch

In [24]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torch.nn import Functional as F

ModuleNotFoundError: No module named 'torch'